<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Unsubscribes</name>
   <tag></tag>
   <elementGuidId>8469a0cf-c7c3-464d-b4a5-bdb5c392d1b6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-widget21__sub</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unsubscribes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[1]/div[1]/div[@class=&quot;m-grid__item m-grid__item--fluid m-grid m-grid--ver-desktop m-grid--desktop m-body&quot;]/div[@class=&quot;m-grid__item m-grid__item--fluid m-wrapper&quot;]/div[@class=&quot;m-content&quot;]/div[3]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-6&quot;]/div[@class=&quot;m-portlet m-portlet--full-height m-portlet--skin-light m-portlet--fit&quot;]/div[@class=&quot;m-portlet__body&quot;]/div[@class=&quot;m-widget21&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-4&quot;]/a[1]/div[@class=&quot;m-widget21__item&quot;]/div[@class=&quot;m-widget21__info&quot;]/span[@class=&quot;m-widget21__sub&quot;]</value>
   </webElementProperties>
</WebElementEntity>
