<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Value</name>
   <tag></tag>
   <elementGuidId>ca6ee1ad-0978-4f8d-950c-40c7ca8cbb31</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Value</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m-datatable--27866229129&quot;)/thead[@class=&quot;m-datatable__head&quot;]/tr[@class=&quot;m-datatable__row&quot;]/th[@class=&quot;m-datatable__cell--center m-datatable__cell m-datatable__cell--sort&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
