<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Card_Subtitle_textarea</name>
   <tag></tag>
   <elementGuidId>6955517c-ca38-4f97-90a0-b81db69fb15b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;List9&quot;]/div/div/div[3]/div[2]/textarea</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@class = 'form-control' and contains(@placeholder, 'Enter subtitle...')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter subtitle</value>
   </webElementProperties>
</WebElementEntity>
