<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TextArea-ListItem1</name>
   <tag></tag>
   <elementGuidId>e13c0f33-2626-47dc-b518-ff5089b7e145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;List1&quot;]/div/div/div[3]/div[1]/div/div[3]/div[1]/center/textarea</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
