<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Filter by Category...Al</name>
   <tag></tag>
   <elementGuidId>4e4c3e4b-a1e0-4b67-9c9b-129b6c9ae223</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m_form_status</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter by Category...AllResearchCustomer BehaviorProduct UseFeedbackEntertain and EngagePromotion UpdatesPlan EventsCustomer satisfactionGreetingsPromotionsInformationFollow-UpSocial MessagetestNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew CategoryNew Category</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m_form_status&quot;)</value>
   </webElementProperties>
</WebElementEntity>
