<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Back</name>
   <tag></tag>
   <elementGuidId>35446ed6-ebd3-4767-911d-63670d4fc582</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m_wizard&quot;)/div[@class=&quot;row m-row--no-padding&quot;]/div[@class=&quot;col-xl-9 col-lg-12 m-portlet m-portlet--tabs&quot;]/div[3]/div[@class=&quot;m-form__actions&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 m--align-left&quot;]/a[@class=&quot;btn btn-secondary m-btn m-btn--custom m-btn--icon&quot;]/span[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
