<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Link_form-control</name>
   <tag></tag>
   <elementGuidId>0dc82a5c-bd43-4773-85b9-b2ba98668c65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;accordion&quot;]/div[2]/div[2]/div/div/div/div[1]/div[2]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;_link_carousel_modal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6&quot;]/div[@id=&quot;cardsContainer&quot;]/div[@id=&quot;accordion&quot;]/div[@class=&quot;panel panel-default&quot;]/div[2]/div[@class=&quot;panel-body&quot;]/div[1]/div[@class=&quot;ui-block&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-10&quot;]/input[@class=&quot;form-control&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_link_carousel_modal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6&quot;]/div[@id=&quot;cardsContainer&quot;]/div[@id=&quot;accordion&quot;]/div[@class=&quot;panel panel-default&quot;]/div[2]/div[@class=&quot;panel-body&quot;]/div[1]/div[@class=&quot;ui-block&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-10&quot;]/input[@class=&quot;form-control&quot;]</value>
   </webElementProperties>
</WebElementEntity>
