<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>code_npx</name>
   <tag></tag>
   <elementGuidId>9506bd47-d335-4b8b-93b9-7143902ffad0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>code</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gatsby-code-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>npx</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;___gatsby&quot;)/div[@class=&quot;css-190hivd&quot;]/div[@class=&quot;css-1tv5sxm css-15lkjjo&quot;]/div[@class=&quot;css-5v0gxc css-95xunl&quot;]/div[@class=&quot;css-12vsfho&quot;]/div[@class=&quot;css-tctv7l&quot;]/div[@class=&quot;css-j4q8zh&quot;]/article[@class=&quot;css-174qq1k&quot;]/div[@class=&quot;css-124oy3v&quot;]/div[@class=&quot;css-51kfyg&quot;]/blockquote[1]/p[2]/code[@class=&quot;gatsby-code-text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
