<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_4</name>
   <tag></tag>
   <elementGuidId>cef93578-7183-4e95-bf2d-0bafe75ab7e9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m_wizard&quot;)/div[@class=&quot;row m-row--no-padding&quot;]/div[@id=&quot;sidebarDiv&quot;]/div[@class=&quot;m-wizard__head&quot;]/div[@class=&quot;m-wizard__nav&quot;]/div[@class=&quot;m-wizard__steps&quot;]/div[4]/div[@class=&quot;m-wizard__step m-wizard__step--current&quot;]/div[@class=&quot;m-wizard__step-info&quot;]/a[@class=&quot;m-wizard__step-number&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='sidebarDiv']/div/div/div/div[4]/div/div/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[4]/div/div/a/span</value>
   </webElementXpaths>
</WebElementEntity>
