<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>polls_category</name>
   <tag></tag>
   <elementGuidId>38bcfc47-44ca-482d-9bd7-5b159b58f5e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]/div/div/div/div[2]/div[3]/div/div[2]/div/div[1]/div/div[2]/div/div/span/span[1]/span/ul/li/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
