<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_AddButton2</name>
   <tag></tag>
   <elementGuidId>03bec908-46d2-42ff-b34d-58ae53e15d22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tab_1&quot;]/div/div[2]/div[2]/div/div[3]/div[2]/div/div[3]/div[1]/div/div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;buttonTarget-1535524332112-2&quot;]/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tab_1&quot;]/div/div[2]/div[2]/div/div[3]/div[2]/div/div[3]/div[1]/div/div</value>
   </webElementProperties>
</WebElementEntity>
