<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1</name>
   <tag></tag>
   <elementGuidId>ca570b6b-aef6-40c8-8924-a554b57bf07d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m_wizard&quot;)/div[@class=&quot;row m-row--no-padding&quot;]/div[@class=&quot;col-xl-3 col-lg-12 m--padding-top-20 m--padding-bottom-15&quot;]/div[@class=&quot;m-wizard__head&quot;]/div[@class=&quot;m-wizard__nav&quot;]/div[@class=&quot;m-wizard__steps&quot;]/div[@class=&quot;m-wizard__step m-wizard__step--current&quot;]/div[@class=&quot;m-wizard__step-info&quot;]/a[@class=&quot;m-wizard__step-number&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
