<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_Card3</name>
   <tag></tag>
   <elementGuidId>02b868ca-61e9-4799-a672-0dcccf9d8a95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tab_1&quot;]/div/div[2]/div[2]/div/div[3]/div[3]/div</value>
   </webElementProperties>
</WebElementEntity>
