<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_7</name>
   <tag></tag>
   <elementGuidId>85821bb5-f8a1-4d4a-a662-514ad73ee2c4</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m_wizard&quot;)/div[@class=&quot;row m-row--no-padding&quot;]/div[@id=&quot;sidebarDiv&quot;]/div[@class=&quot;m-wizard__head&quot;]/div[@class=&quot;m-wizard__nav&quot;]/div[@class=&quot;m-wizard__steps&quot;]/div[@class=&quot;m-wizard__step m-wizard__step--current&quot;]/div[@class=&quot;m-wizard__step-info&quot;]/a[@class=&quot;m-wizard__step-number&quot;]/span[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
