<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Test2</name>
   <tag></tag>
   <elementGuidId>95e790eb-0b75-4813-8f39-7a62f493007c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-nav__link-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[1]/div[1]/div[@class=&quot;m-grid__item m-grid__item--fluid m-grid m-grid--ver-desktop m-grid--desktop m-body&quot;]/div[@class=&quot;m-grid__item m-grid__item--fluid m-wrapper&quot;]/div[@class=&quot;m-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;m-portlet&quot;]/div[@class=&quot;m-portlet__body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 col-md-4 col-sm-4&quot;]/div[@class=&quot;m-dropdown m-dropdown--inline m-dropdown--arrow m-dropdown--open&quot;]/div[@class=&quot;m-dropdown__wrapper&quot;]/div[@class=&quot;m-dropdown__inner&quot;]/div[@class=&quot;m-dropdown__body&quot;]/div[@class=&quot;m-dropdown__content&quot;]/ul[@class=&quot;m-nav&quot;]/li[@class=&quot;m-nav__item&quot;]/a[@class=&quot;m-nav__link&quot;]/span[@class=&quot;m-nav__link-text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
