<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>csv_file</name>
   <tag></tag>
   <elementGuidId>49c16019-e644-4837-aa7a-b290e965e03c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]/div/div/div/div[2]/div[3]/div[2]/div[3]/div/div/div[2]/div[2]/div/div/div[2]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type=&quot;file&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@type=&quot;file&quot;]</value>
   </webElementProperties>
</WebElementEntity>
