<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mark_Subscribe</name>
   <tag></tag>
   <elementGuidId>495e71f3-cf9a-4f37-a89a-6a2138ac3436</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mark</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subscribe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[1]/div[1]/div[@class=&quot;m-grid__item m-grid__item--fluid m-grid m-grid--ver-desktop m-grid--desktop m-body&quot;]/div[2]/div[@class=&quot;m-grid__item m-grid__item--fluid m-wrapper&quot;]/div[@class=&quot;m-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-3&quot;]/div[@class=&quot;m-portlet m-portlet--full-height&quot;]/div[@class=&quot;m-portlet__body&quot;]/div[@class=&quot;m-widget4&quot;]/div[@class=&quot;m-widget4__item&quot;]/div[@class=&quot;m-widget4__info&quot;]/div[1]/span[@class=&quot;m-widget4__title&quot;]/span[1]/mark[@class=&quot;&quot;]</value>
   </webElementProperties>
</WebElementEntity>
